
namspace: datalama-microservice-namespace

replicaCount: 1

image:
  repository: ghcr.io/schmenniooo/datalama
  pullPolicy: IfNotPresent
  tag: "latest"

podAnnotations: {}
podLabels: {}

resources:                                                                           
  requests:                                                                          
    cpu: "100m"                                                                      
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

serviceAccount:
  create: true
  automount: true
  name: "datalama-user-service-account"

# Running the container as non-root user for security
podSecurityContext:                                                                  
  runAsNonRoot: true                                                                 
  runAsUser: 1000
  runAsGroup: 1000

# Security context for the container to further restrict permissions
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 3000

livenessProbe:
  httpGet:
    path: /ping
    port: 3000
readinessProbe:
  httpGet:
    path: /ping
    port: 3000
