
namespace: datalama-microservice-namespace

replicaCount: 1

# Image on GH: https://github.com/schmenniooo/DataLama/pkgs/container/datalama
image:
  repository: ghcr.io/schmenniooo/datalama
  pullPolicy: IfNotPresent
  tag: "latest"

# Environment variables for the datalama microservice container
environmentVariables:
  - name: "API_KEY_FIELD_NAME"
    value: "X-API-Key"
  - name: "API_KEY"
    value: "your_api_key_here"
  - name: "OLLAMA_BASE_URL"
    value: "http://localhost:11434"
  - name: "OLLAMA_MODEL"
    value: "llama3.2"
  - name: "DEBUG"
    value: "false"
  - name: "HOST"
    value: "0.0.0.0"
  - name: "PORT"
    value: "3000"

# TODO: Check if practical
podAnnotations: {}
podLabels: {}

resources:                                                                           
  requests:                                                                          
    cpu: "100m"                                                                      
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

serviceAccount:
  create: true
  automount: true
  name: "datalama-user-service-account"

# Running the container as non-root user for security
podSecurityContext:                                                                  
  runAsNonRoot: true                                                                 
  runAsUser: 1000
  runAsGroup: 1000

# Security context for the container to further restrict permissions
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 3000

livenessProbe:
  httpGet:
    path: /health
    port: 3000
readinessProbe:
  httpGet:
    path: /health
    port: 3000

# Traefik Reverse proxy Configuration

# Enables the dashboard in Secure Mode
api:
  dashboard: true
  insecure: false

# Creates a BasicAuth Middleware and Secret for the Dashboard Security
extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: "P@ssw0rd"      # Replace with an Actual Password
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: dashboard-auth
    spec:
      basicAuth:
        secret: dashboard-auth-secret

ports:
  # Defines the HTTP entry point named 'web'
  web:
    port: 80
    nodePort: 30000
    # Instructs this entry point to redirect all traffic to the 'websecure' entry point
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  # Defines the HTTPS entry point named 'websecure'
  websecure:
    port: 443
    nodePort: 30001

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.docker.localhost`)
    entryPoints:
      - websecure
    middlewares:
      - name: dashboard-auth

# Enable Observability
logs:
  general:
    level: INFO
  # This enables access logs, outputting them to Traefik's standard output by default. The [Access Logs Documentation](https://doc.traefik.io/traefik/observability/access-logs/) covers formatting, filtering, and output options.
  access:
    enabled: true

# Enables Prometheus for Metrics
metrics:
  prometheus:
    enabled: true
