name: test-push-helm-chart

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
    test:
        name: test-helm-chart
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Helm
              uses: azure/setup-helm@v3

            - name: Linting Helm Chart
              run: helm lint ./helm/datalama
            
            - name: Testing Helm Chart
              run: helm template datalama ./helm/datalama
