name: build-test-python-package

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
    build:
        name: build-python-package
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'
                
            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: uv sync --no-dev

            - name: Build package
              run: uv build

    test:
        name: test-python-package
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13'
                
            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: uv sync

            - name: Run tests
              run: uv run pytest ./tests
    