name: create-release

on:
    workflow_run: 
      workflows:                                                                                                                                                                   
        - "build-push-docker-image"                                                                                                                                                
        - "test-push-helm-chart"
    push:
        branches: [ "main" ]

permissions:
    contents: write
    packages: read

jobs: 
    create-release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                name: helm-chart
                path: helm-chart

            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                name: docker-image
                path: docker-image

            - name: Create GitHub Release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ github.ref_name }}
                name: Release ${{ github.ref_name }}
                artifacts: |
                    helm-chart/datalama-chart-*.tgz
                    docker-image/image.tar.gz
                